### ISSUE TITLE
Migrate to Equinix Labs repo for more visibility

### ISSUE THREAD

**Issue by jacobsmith928** [equinix-labs/not_ipmi_to_metal#1]
Hey @dlotterman would this make sense to migrate to Equinix Labs?

**Comment by dlotterman** [comment]
@jacobsmith928 Just following up for the transcript. I think this should now be in a place where it's ready for [Equinix Labs](https://github.com/equinix-labs), I'll work with the right team to get that going.

**Comment by vielmetti** [comment]
This project is now under the Equinix Labs top level repo, at https://github.com/equinix-labs/not_ipmi_to_metal , so this task is complete. Closing as done.
