### ISSUE TITLE
Python version needed?

### ISSUE THREAD

**Issue by vielmetti** [equinix-labs/not_ipmi_to_metal#2]
Is there any specific version of Python (2, 3, any point release) that is needed for this code to work? I expected to see a statement to that effect in the README file (but I might be missing it elsewhere). thanks Ed

**Comment by displague** [comment]
Python2 support ended in January 2020. If the project is unclear, I'd opt to set an expectation that Python 3 is required.

**Comment by vielmetti** [comment]
The project docs read:

> This project assumes a current python3 install and works inside of a virtualenv, the Python that comes packaged with Ubuntu 22.04 or CentOS 8 or newer should work fine.

which is a clear statement for the reader. Closing as done.
